### PR TITLE
library_benchmark_group! change mod to pub

### PR DESCRIPTION
**Pull request by ryanpeach**

### CODE REVIEW

**Comment by ryanpeach** [comment]
Hmm. Does 1.67.1 always fail? Looks like more private functions.

**Comment by gamma0987** [comment]
The ui tests run only with the msrv. Most of the time, only the error fixtures need to be updated. You can do so with `TRYBUILD=overwrite just test-ui` and then check the diff.

**Comment by ryanpeach** [comment]
Learning a lot of features from your `Justfile`. I use `just` but never wrote one this complicated. Cool stuff.

**Comment by ryanpeach** [comment]
@gamma0987 Is this what you needed? https://github.com/iai-callgrind/iai-callgrind/pull/300/commits/fab62750679e272beed497efea269bae362fb859

**Comment by ryanpeach** [comment]
I'm unsure how to resolve these build errors. Maybe you could take over? Maybe it needs to be run with a certain version of rust to get the desired stderr?

**Comment by gamma0987** [comment]
yep, I somehow like the `just` format and learn something new myself every time I have to add something to the Justfile.

> Is this what you needed? https://github.com/iai-callgrind/iai-callgrind/commit/fab62750679e272beed497efea269bae362fb859

Almost. The ui tests need to be run with the msrv. The compiler error messages between the rust toolchains differ quiet a lot so they are fixed to the msrv.

**Comment by gamma0987** [comment]
> Maybe you could take over?

Shall I?

**Comment by gamma0987** [comment]
Thanks :)

**Pull request merged**
